name: mdsoft_google_map_routing
description: "A powerful Flutter package for real-time navigation and route
  tracking using Google Maps API. This package supports background location
  updates, route calculation, and customizable map styles."
version: 0.0.6
homepage: "https://github.com/Salah3mer/mdSoftGoogleMapRouting.git"

environment:
  sdk: ^3.4.2
  flutter: ">=3.3.0"

dependencies:
  dartz: ^0.10.1
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.1
  flutter_background_service_ios: ^5.0.3
  flutter_bloc: ^9.1.1
  flutter_polyline_points: ^3.1.0
  google_maps_flutter: ^2.13.1
  google_maps_flutter_web: ^0.5.14+2
  location: ^8.0.1
  plugin_platform_interface: ^2.1.8
  socket_io_client: ^3.1.2
  toastification: ^3.0.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass
  assets:
    - assets/images/
